packages:
  - packages/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - esbuild
  - unrs-resolver
catalog:
  '@antfu/eslint-config': 6.7.1
  '@mdi/js': 7.4.47
  '@nestjs/cli': 11.0.14
  '@nestjs/common': 11.1.9
  '@nestjs/config': 4.0.2
  '@nestjs/core': 11.1.9
  '@nestjs/platform-express': 11.1.9
  '@nestjs/serve-static': 5.0.4
  '@nestjs/testing': 11.1.9
  '@nestjs/typeorm': 11.0.0
  '@semantic-release/changelog': 6.0.3
  '@semantic-release/git': 10.0.1
  '@semantic-release/github': 12.0.2
  '@semantic-release/npm': 13.1.2
  '@swc/core': 1.15.3
  '@tsconfig/node22': 22.0.5
  '@types/express': 5.0.6
  '@types/jsdom': 27.0.0
  '@types/multer': 2.0.0
  '@types/node': 24.10.3
  '@types/supertest': 6.0.3
  '@vitejs/plugin-vue': 6.0.2
  '@vitest/coverage-v8': 3.2.4
  '@vue/eslint-config-typescript': 14.6.0
  '@vue/test-utils': 2.4.6
  '@vue/tsconfig': 0.8.1
  '@vueuse/core': 14.1.0
  class-transformer: 0.5.1
  class-validator: 0.14.3
  dotenv: 17.2.3
  eslint: 9.39.1
  fs-extra: 11.3.2
  jiti: 2.6.1
  jsdom: 27.3.0
  npm-run-all2: 8.0.4
  pg: 8.16.3
  pinia: 3.0.4
  puppeteer: 24.33.0
  reflect-metadata: 0.2.2
  resize-observer-polyfill: 1.5.1
  rxjs: 7.8.2
  start-server-and-test: 2.1.3
  supertest: 7.1.4
  ts-loader: 9.5.4
  ts-node: 10.9.2
  tsconfig-paths: 4.2.0
  tsup: 8.5.1
  typeorm: 0.3.28
  typescript: 5.9.3
  vite: 7.2.7
  vite-plugin-vue-devtools: 8.0.5
  vite-plugin-vuetify: 2.1.2
  vitest: 3.2.4
  vue: 3.5.25
  vue-router: 4.6.4
  vue-tsc: 3.1.8
  vuetify: 3.11.3
