import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const API_URL = 'https://usetrmnl.com/api'
const target = path.join(path.dirname(fileURLToPath(import.meta.url)), '../src/device-models/data/trmnl-snapshot.ts')

async function fetchData(endpoint) {
  const res = await fetch(`${API_URL}/${endpoint}`)
  if (!res.ok)
    throw new Error(`Failed to fetch ${endpoint}: ${res.status} ${res.statusText}`)
  const { data } = await res.json()
  return data
}

const MODEL_KEYS = ['name', 'label', 'description', 'width', 'height', 'colors', 'bit_depth', 'scale_factor', 'rotation', 'mime_type', 'offset_x', 'offset_y', 'kind', 'palette_ids', 'image_size_limit', 'css']
const PALETTE_KEYS = ['id', 'name', 'grays', 'colors', 'framework_class', 'grayscale_bit_depth']

const pick = keys => item => Object.fromEntries(keys.filter(key => item[key] !== undefined).map(key => [key, item[key]]))

const [models, palettes] = await Promise.all([
  fetchData('models').then(items => items.map(pick(MODEL_KEYS))),
  fetchData('palettes').then(items => items.map(pick(PALETTE_KEYS))),
])

const banner = `// Generated by scripts/update_device_model_snapshot.mjs from ${API_URL} on ${new Date().toISOString().slice(0, 10)}.
// Offline seed for the device model reference tables; the live sync overrides it.
`

const body = `import type { TrmnlModelPayload, TrmnlPalettePayload } from '../trmnl-payloads'

export const TRMNL_PALETTES_SNAPSHOT: TrmnlPalettePayload[] = ${JSON.stringify(palettes, null, 2)}

export const TRMNL_MODELS_SNAPSHOT: TrmnlModelPayload[] = ${JSON.stringify(models, null, 2)}
`

fs.writeFileSync(target, banner + body)
execFileSync('npx', ['eslint', '--fix', target], { stdio: 'inherit' })
console.log(`Wrote ${models.length} models and ${palettes.length} palettes to ${target}`)
