name: Checks

on:
  workflow_call:
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Type Check
        run: pnpm run type-check
      - name: Test
        run: pnpm run test
      - name: Build
        run: pnpm run build